### ISSUE TITLE
another backbone architecture

### ISSUE THREAD

**Issue by benlee73** [phamquiluan/publaynet#11]
hi
You only used the MaskRCNN-Resnet50-FPN architecture.   
I think other architectures (like resnext 101) will have better performance.   
Is there any reason you haven't used a different architecture?   
thank you very much.

**Comment by phamquiluan** [comment]
@benlee73, time and money. send me the money and I will train that model for you :heart:
```
XRP Address: rEb8TK3gBgk5auZkwc6sHnwrGVJH8DuaLh
XRP Tag: 104808637

BTC Address: 1DnqYU7efJ1hyusW4Vx6vsx3mXMXmrmVCg

USDT Address (ERC20): 0x87414eb3f9b49af40c8e57a3162bd6432a113109
```

**Comment by benlee73** [comment]
It's funny. I'll do it! I'll just ask you one more question

After training that model, I want to get mAP.  
And maybe i should implement the code for it.  
Can you give me any information on how to get it?

**Comment by benlee73** [comment]
hi I found out that there is a code to calculate AP in the code provided.
   
I have a question. What is the meaning of the variable IS_SM? thank you

**Comment by benlee73** [comment]
hi.
I'm sorry for asking too many questions.
I evaluated the performance of model_196000.pth provided by training_code/evaluate.py.
But I got the results below.

AP: 0.5561782141239605
AP50: 0.6230051957927281
AP75: 0.5951028558281898
AP_small: 0.37807909623881614
AP_medium: 0.47915292681869626
AP_large: 0.5924650938620369

Why did you get such low results?

**Comment by benlee73** [comment]
Solved the problem!
There was a problem with my dataset.
Thank you very much.
